// const purgecss = [
//   "@fullhuman/postcss-purgecss",
//   {
//     // Specify the paths to all of the template files
//     content: [
//       "./src/pages/**/*.{js,jsx,ts,tsx}",
//       "./src/components/**/*.{js,jsx,ts,tsx}",
//       "./src/pages/*.{js,jsx,ts,tsx}",
//       "./src/components/*.{js,jsx,ts,tsx}",
//     ],
//     defaultExtractor: content => content.match(/[\w-/:]+(?<!:)/g) || [],
//     safelist: [
//       "html",
//       "body",
//       /w-/,
//       /list-/,
//       /-link/,
//       /gray-link/,
//       /DayPicker/,
//       /text-gray/,
//       /sm:hidden/,
//       /sm:block/,
//       /md:hidden/,
//       /md:block/,
//       /lg:hidden/,
//       /lg:block/,
//       /xl:hidden/,
//       /xl:block/,
//       /opacity/,
//       /flex-row/,
//       /bg-white/,
//       /w-80/,
//       /h-80/,
//       /h-120/,
//       /h-240/,
//       /p-0/,
//       /p-8/,
//       /p-6/,
//       /p-16/,
//       /pl-8/,
//       /pr-8/,
//       /mr-4/,
//       /justify-end/,
//       /xl:pl-8/,
//       /BrainhubCarousel/,
//       /bg-columbia/,
//       /bg-blue-900/,
//       /text-blue-400/,
//       /text-blue-500/,
//       /shadow-flat-card/,
//     ],
//   },
// ]

module.exports = {
  plugins: [
    "tailwindcss",
    // process.env.NODE_ENV === "production" ? purgecss : undefined,
    "postcss-preset-env",
  ],
}
